### ISSUE TITLE
Black GUI

### ISSUE THREAD

**Issue by Akull9** [EwyBoy/EwysWorkshop#1]
I submitted this issue a while ago on the other Steve's Workshop Git; could you possibly address this issue?
https://github.com/Vswe/Production/issues/27

**Comment by EwyBoy** [comment]
Is it still a issue for you? I will look into it

**Comment by ljfa-ag** [comment]
I'm having the same issue, must be some video-card-specific weirdness.
Setting the background color to white before drawing the GUI texture should fix it.
