### ISSUE TITLE
HQM Doesn't detect crafting tasks

### ISSUE THREAD

**Issue by JasonMcRay** [EwyBoy/EwysWorkshop#15]
###### **Forge Version & Ewy's Workshop Version**
Forge: 10.13.4.1614 (MC 1.7.10)
Ewy: 1.1.4
HQM: 4.4.4

###### **Expected behavior**
When crafting items in EW it should count towards crafting in HQM quests

###### **Actual Behavior**
Crafting in EW does not count towards HQM quests

###### **Link to Crashlog or Forgelog** *[If Applicable]*
None

###### **Steps to reproduce** *[If Applicable]*
1) Have a HQM quest which requires crafting something
2) Try to craft that thing in EW table
3) It does not count towards completion

**Comment by JorVaCoding** [comment]
I'll take a look into this, I know some of our event handlers are a bit buggy... It's possible that it's just fixed for 1.9/1.10+ because 1.7 modpacks are starting to die down and we're trying to focus our time on a stable 1.10 build

**Comment by JasonMcRay** [comment]
Just to add in... Players remember it was possible and it worked in previous version of Ewys Workshop to complete quests. My modpack used version 1.1.2 for a long time and it was fine in them. We recently updated to 1.1.4 (due to existing dupe bug) and it started to happen at that point.

**Comment by JorVaCoding** [comment]
Found the issue, we removed the calling of the event because it created errors in the console (1.1.3)... I don't know if there is a way to work around this and fix both bugs; Will look into, but might be 1.10+ because 1.7 support is quickly dying.

**Comment by JorVaCoding** [comment]
Issue: #3
Pull request: #14

**Comment by JasonMcRay** [comment]
@JorVaCoding This (the spam on autocrafting) has been issue in VSWE version, yes. But it can be fixed by: https://github.com/Vswe/Production/pull/31/files

I forked Ewys Workshop, did the change and no error spam in the log and HQM detects the crafting just fine (of course it does not detect if the item is autocrafted).

I don't see any reason it will break anything.

(Made a PR - see below)

in short it fires the playerCrafting event only when player is not null
