### ISSUE TITLE
One recipe seems to be wrong

### ISSUE THREAD

**Issue by BakermanLP** [EwyBoy/EwysWorkshop#4]
Hello there,

I found a little problem in your mod, btw it was Hardcore Ender Expansion that found the recipe problem. It seems, that you register a recipe in the following code line:
/src/main/java/com/ewyboy/ewysworkshop/loaders/RecipeLoader.java#L32

But in my NEI, I don't see this barrel.

Could you have a look into it.

Thanks

Michael (aka BakermanLP)

**Comment by EwyBoy** [comment]
That was a VIP barrel that got canceled
