### ISSUE TITLE
Worktable continuously causes chunk updates, killing FPS

### ISSUE THREAD

**Issue by BlayTheNinth** [EwyBoy/EwysWorkshop#7]
The worktable (upgrades don't matter, happens to an empty one as well) is causing continuous chunk updates (showing as 80 chunk updates in F3), dropping FPS a whole bunch (from 60 to 40 for me).

Happens on Minecraft 1.7.10, Forge 10.13.4.1614, Ewy's Workshop 1.1.1

**Comment by wrathlamp** [comment]
I second this.  incoming mod list.
minecraft forge 10.13.4.1558.  mine is a variation on the mega computer pack found on technic launcher. (using multiMC to launch) if you want any specifics, please ask. love this mod, and normaly it
does not do this.

**Comment by JasonMcRay** [comment]
Fair amount of players of my Modpack (InfiTech 2) has also reported almost 50% FPS drop when the Workshop Table is present. Forge 1614, Workshop 1.1.1. This was not an issue in Steve's Production (there were other issues, that made me to switch to your mod)

**Comment by EwyBoy** [comment]
I believe this issue has been fixed now.

I finally figured it out what could cause such heavy FPS drop and chunck updates.

I was forcing a block update every single time the entity ticked (20 times per second or so).

Patch can be found here: http://minecraft.curseforge.com/projects/ewys-workshop/files
