### ISSUE TITLE
Update repo

### ISSUE THREAD

**Issue by Jakja2** [EwyBoy/EwysWorkshop#8]
Hello, I noticed that version 1.1.2 of this mod was released. I was wondering if you'd be able to update this repo to represent that.

Thank you!

**Comment by JorVaCoding** [comment]
We are currently in the process of updating to 1.10 and having a repo with the new updates... I'll post back here once the repo is fully setup with branches, and I'll leave a link on this comment.

**Comment by Jakja2** [comment]
Thank you for reply, 

The reason I wanted to try to get the source for 1.1.2 was because a dupe was discovered using that version and I wanted to attempt to fix it.

I'll open a new issue about that dupe so you could hopefully fix it.

**Comment by JorVaCoding** [comment]
The repo has been updated, and that dupe bug is our main priority right now.
