### ISSUE TITLE
Ewy's Workshop Table Dupe

### ISSUE THREAD

**Issue by Jakja2** [EwyBoy/EwysWorkshop#9]
If you add the crafting table to the workshop and then put a recipe into the crafting table, but don't take the result, then break the table and you will get both the items in the recipe and the result back.

**Comment by EwyBoy** [comment]
ohh, this bug have to get fixed! Thanks for the info

**Comment by JorVaCoding** [comment]
Version 1.1.3 has the updated code and has a fix for this. :+1: smile:
